= SaeMoim Rest Docs
:toc: left
:toclevels: 2
:source-highlighter: highlightjs

== 1. Admin API

=== 1-1. 관리자 로그인

operation::admin/sign-in[snippets = 'http-request,request-fields,http-response,response-headers,response-fields']

=== 1-2. 관리자 계정 목록 조회

operation::admin/getAll[snippets = 'http-request,request-headers,http-response,response-fields']

=== 1-3. 관리자 계정 생성

operation::admin/create[snippets = 'http-request,request-headers,request-fields,http-response,response-fields']

=== 1-4. 관리자 계정 삭제

operation::admin/delete[snippets = 'path-parameters,http-request,request-headers,http-response,response-fields']

=== 1-5. 관리자 토큰 연장

operation::admin/reissue[snippets = 'http-request,request-headers,http-response,response-headers,response-fields']

== 2. Blacklist API

=== 2-1. 블랙리스트 조회

operation::blacklist/getAll[snippets='http-request,request-headers,http-response,response-fields']

=== 2-2. 블랙리스트 등록

operation::blacklist/add[snippets='path-parameters,http-request,request-headers,http-response,response-fields']

=== 2-3. 블랙리스트 영구 등록

operation::blacklist/addPermanent[snippets='path-parameters,http-request,request-headers,http-response,response-fields']

=== 2-4. 블랙리스트 해제

operation::blacklist/delete[snippets='path-parameters,http-request,request-headers,http-response,response-fields']

== 3. Category API

=== 3-1. 카테고리 조회

operation::category/getAll[snippets='http-request,http-response,response-fields']

=== 3-2. 상위카테고리 생성

operation::category/createParent[snippets='http-request,request-headers,request-fields,http-response,response-fields']

=== 3-3. 하위 카테고리 생성

operation::category/createChild[snippets='path-parameters,http-request,request-headers,request-fields,http-response,response-fields']

=== 3-4. 카테고리 수정

operation::category/update[snippets='path-parameters,http-request,request-headers,request-fields,http-response,response-fields']

=== 3-5. 카테고리 삭제

operation::category/delete[snippets='path-parameters,http-request,request-headers,http-response,response-fields']

== 4. User API

=== 4-1. 회원가입

operation::user/sign-up[snippets='http-request,request-fields,http-response,response-fields']

=== 4-2. 이메일 중복 검사

operation::user/email-check[snippets='http-request,request-fields,http-response,response-fields']

=== 4-3. 닉네임 중복 검사

operation::user/username-check[snippets='http-request,request-fields,http-response,response-fields']

=== 4-4. 로그인

operation::user/login[snippets='http-request,request-fields,http-response,response-headers,response-fields']

=== 4-5. 로그아웃

operation::user/logout[snippets='http-request,request-headers,http-response,response-fields']

=== 4-6. 토큰 재발급

operation::user/reissue[snippets='http-request,request-headers,http-response,response-headers,response-fields']

=== 4-7. 내 정보 조회

operation::user/myProfile[snippets='http-request,request-headers,http-response,response-fields']

=== 4-8. 내 정보 수정

operation::user/update-profile[snippets='http-request,request-headers,request-part-requestDto-fields,http-response,response-fields']

=== 4-9. 사용자 정보 조회

operation::user/user-info[snippets='http-request,request-headers,http-response,response-fields']

=== 4-10. 회원 프로필 조회

operation::user/profile[snippets='http-request,request-headers,http-response,response-fields']

=== 4-11. 전체 회원 조회

operation::user/getAll[snippets='http-request,request-headers,http-response,response-fields']

=== 4-12. 회원 탈퇴

operation::user/withdrawal[snippets='http-request,request-headers,request-fields,http-response,response-fields']
